const configuredPlatformName = process.env.NEXT_PUBLIC_PLATFORM_NAME?.trim();

export const PLATFORM_NAME = configuredPlatformName || "CrickiERP";

export const BRANDING = {
  adminTitle: `${PLATFORM_NAME} Admin`,
  adminDescription: `${PLATFORM_NAME} admin frontend`,
  loginDescription: `${PLATFORM_NAME} admin login`,
  poweredByText: `Powered by ${PLATFORM_NAME}`,
  generatedBySystemText: `Generated by ${PLATFORM_NAME} System`,
  liabilitySummaryTitle: `${PLATFORM_NAME} Liability Summary`,
  liabilitySuiteFooter: `Proprietary & Confidential - ${PLATFORM_NAME} Financial Suite`,
} as const;
